# Generated by Django 3.2.4 on 2021-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(default='choice', max_length=255),
        ),
    ]
