# Generated by Django 3.2.4 on 2021-06-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210616_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.choice'),
        ),
    ]
