# Generated by Django 3.2.4 on 2021-06-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210616_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quiz'),
        ),
    ]
