# Generated by Django 3.2.4 on 2021-06-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_choice_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quiz_id',
            new_name='quizid',
        ),
    ]
