# Generated by Django 3.2.4 on 2021-06-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_quiz_id_choice_quizid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quizid',
            new_name='quiz_id',
        ),
    ]
