# Generated by Django 3.2.4 on 2021-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_quizid_choice_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='maximum_mark',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
