# Generated by Django 3.2.4 on 2021-06-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_questionpaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionBank',
        ),
        migrations.RenameModel(
            old_name='QuestionPaper',
            new_name='Questions',
        ),
    ]
