# Generated by Django 3.2.4 on 2021-06-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210616_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuizQuestions',
        ),
    ]
