# Generated by Django 3.2.4 on 2021-06-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_rename_questions_quizquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('objective_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='single', max_length=255)),
                ('maximum_mark', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question'),
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
