# Generated by Django 3.2.4 on 2021-06-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210617_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='quiz.Question'),
        ),
    ]
