# Generated by Django 3.2.4 on 2021-06-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
