# Generated by Django 3.2.4 on 2021-06-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_question_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_explantion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
